from enum import Enum


class Role(str, Enum):
    PATIENT = "PATIENT"
    RECEPTIONIST = "RECEPTIONIST"
    DOCTOR = "DOCTOR"
    ADMIN = "ADMIN"


class DoctorStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    IN_CONSULTATION = "IN_CONSULTATION"
    ON_BREAK = "ON_BREAK"
    OFFLINE = "OFFLINE"
    FULLY_BOOKED = "FULLY_BOOKED"


class AppointmentStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    ARRIVED = "ARRIVED"
    IN_CONSULTATION = "IN_CONSULTATION"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class QueueEntryStatus(str, Enum):
    WAITING = "WAITING"
    IN_CONSULTATION = "IN_CONSULTATION"
    COMPLETED = "COMPLETED"
    NO_SHOW = "NO_SHOW"
    REMOVED = "REMOVED"


class Urgency(str, Enum):
    URGENT = "URGENT"
    PRIORITY = "PRIORITY"
    ROUTINE = "ROUTINE"


class CareCategory(str, Enum):
    GENERAL_MEDICINE = "GENERAL_MEDICINE"
    GASTROENTEROLOGY = "GASTROENTEROLOGY"
    GYNECOLOGY = "GYNECOLOGY"
    PEDIATRICS = "PEDIATRICS"
    NEUROLOGY = "NEUROLOGY"


class NotificationType(str, Enum):
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
    QUEUE_UPDATED = "QUEUE_UPDATED"
    DOCTOR_DELAY = "DOCTOR_DELAY"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    PRIORITY_ALERT = "PRIORITY_ALERT"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"


class PaymentStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
